### ISSUE TITLE
fix[homebrew-formulae]: error on install: "formulae require at least a URL"

### ISSUE THREAD

**Issue by BlueFalconHD** [KenanBek/dbui#48]
**Describe the bug**
The formulae doesn't install. The full error is:
```
Error: formulae require at least a URL 
/opt/homebrew/Library/Homebrew/formula.rb:283:in `determine_active_spec'
/opt/homebrew/Library/Homebrew/formula.rb:214:in `initialize'
/opt/homebrew/Library/Homebrew/formulary.rb:308:in `new'
/opt/homebrew/Library/Homebrew/formulary.rb:308:in `get_formula'
/opt/homebrew/Library/Homebrew/formulary.rb:561:in `factory'
/opt/homebrew/Library/Homebrew/cli/parser.rb:634:in `block in formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:630:in `map'
/opt/homebrew/Library/Homebrew/cli/parser.rb:630:in `formulae'
/opt/homebrew/Library/Homebrew/cli/parser.rb:307:in `parse'
/opt/homebrew/Library/Homebrew/cmd/install.rb:147:in `install'
/opt/homebrew/Library/Homebrew/brew.rb:97:in `<main>'
```
**To Reproduce**
1. Open any terminal on macOS
2. Run `brew tap kenanbek/dbui && brew install dbui`

**Expected behavior**
The formulae should install dbui.

**Screenshots**

**Environment (please complete the following information):**
 - OS `Darwin/macOS`
 - Terminal `n/a`
 - Version `13.1`

**Additional context**

**Comment by cgimenes** [comment]
I'm suspecting of Apple's Silicon, is your CPU Intel-based?

**Comment by BlueFalconHD** [comment]
Nope, apple silicon

**Comment by cgimenes** [comment]
Then, that's it. We don't have a brew formula working for Apple silicon yet 😞

**Comment by KenanBek** [comment]
Fixed and verified end-to-end with v0.9.0: the formula's missing-URL failure on Apple Silicon is gone — releases now publish a cask with on_arm/on_intel blocks to the KenanBek/homebrew-dbui tap. Verified on an M-series Mac: `brew tap kenanbek/dbui && brew install dbui` installs, and `dbui -version` reports 0.9.0. (If you had the old in-repo tap: `brew untap kenanbek/dbui` once, then re-tap.)
